// Modal
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';

// Auth
export const LOGIN = 'AUTH_LOGIN';
export const LOGOUT = 'AUTH_LOGOUT';

// Homepage
export const HOMEPAGE_SET_COURSES = 'HOMEPAGE_SET_COURSES';
export const HOMEPAGE_SET_SOURCE_LANGUAGES = 'HOMEPAGE_SET_SOURCE_LANGUAGES';
export const HOMEPAGE_SET_CURRENT_LANGUAGE = 'HOMEPAGE_SET_CURRENT_LANGUAGE';
export const HOMEPAGE_STOP_LOADING = 'HOMEPAGE_STOP_LOADING';

// User
export const USER_SET_CURRENT_COURSE = 'USER_SET_CURRENT_COURSE';
export const USER_SET_USER_COURSES = 'USER_SET_USER_COURSES';
export const USER_SET_OTHER_COURSES = 'USER_SET_OTHER_COURSES';

// Dictionary
export const DICTIONARY_SET_USER_VOCABULARIES = 'DICTIONARY_SET_USER_VOCABULARIES';
export const DICTIONARY_SET_VOCABULARY_GROUPS = 'DICTIONARY_SET_VOCABULARY_GROUPS';
export const DICTIONARY_SET_PROGRESS = 'DICTIONARY_SET_PROGRESS';
