// Modal
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';

// User
export const USER_SET_COURSES = 'USER_SET_COURSES';
export const USER_HOMEPAGE_LOAD_COURSES = 'USER_HOMEPAGE_LOAD_COURSES';
export const USER_HOMEPAGE_CHANGE_LANGUAGE = 'USER_HOMEPAGE_CHANGE_LANGUAGE';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_AUTH_LOADED = 'USER_AUTH_LOADED';

// Dictionary
export const DICTIONARY_UPDATE = 'DICTIONARY_UPDATE';
export const DICTIONARY_SET_VOCABULARIES = 'DICTIONARY_SET_VOCABULARIES';
export const DICTIONARY_SET_PROGRESS = 'DICTIONARY_SET_PROGRESS';

export const DICTIONARY_SET_VOCABULARY = 'DICTIONARY_SET_VOCABULARY';
export const DICTIONARY_SET_USER_VOCABULARY = 'DICTIONARY_SET_USER_VOCABULARY';
export const DICTIONARY_SET_USER_WORDS = 'DICTIONARY_SET_USER_WORDS';
export const DICTIONARY_SET_FILTER_TEXT = 'DICTIONARY_SET_FILTER_TEXT';
export const DICTIONARY_SET_FILTER_TRAINING = 'DICTIONARY_SET_FILTER_TRAINING';
export const DICTIONARY_SET_FILTER_PROGRESS = 'DICTIONARY_SET_FILTER_PROGRESS';

// Training
export const TRAINING_SET_COUNT = 'TRAINING_SET_COUNT';
export const TRAINING_SET_AVAILABLE_VOCABULARIES = 'TRAINING_SET_AVAILABLE_VOCABULARIES';

export const TRAINING_START = 'TRAINING_START';
export const TRAINING_CLEAR = 'TRAINING_CLEAR';

export const TRAINING_ANSWER_CORRECT = 'TRAINING_ANSWER_CORRECT';
export const TRAINING_ANSWER_WRONG = 'TRAINING_ANSWER_WRONG';
export const TRAINING_ANSWER_MISTAKE = 'TRAINING_ANSWER_MISTAKE';
export const TRAINING_ANSWER_LETTER_CORRECT = 'TRAINING_ANSWER_LETTER_CORRECT';
export const TRAINING_ANSWER_LETTER_MISTAKE = 'TRAINING_ANSWER_LETTER_MISTAKE';
export const TRAINING_ANSWER_CLEAR_LETTER_MISTAKE = 'TRAINING_ANSWER_CLEAR_LETTER_MISTAKE';
export const TRAINING_ANSWER_SKIP = 'TRAINING_ANSWER_SKIP';
export const TRAINING_NEXT_STEP = 'TRAINING_NEXT_STEP';
export const TRAINING_COMPLETE = 'TRAINING_COMPLETE';

// Stories
export const STORIES_SET_STORIES = 'STORIES_SET_STORIES';

export const STORIES_LOAD_STORY = 'STORIES_SET_STORY';
export const STORIES_CLEAR_STORY = 'STORIES_CLEAR_STORY';
export const STORIES_SET_SELECTED_WORD = 'STORIES_SET_SELECTED_WORD';
export const STORIES_SET_TRANSLATIONS = 'STORIES_SET_TRANSLATIONS';
export const STORIES_ADD_WORD = 'STORIES_ADD_WORD';
export const STORIES_REMOVE_WORD = 'STORIES_REMOVE_WORD';
export const STORIES_COMPLETE_STORY = 'STORIES_COMPLETE_STORY';
